---
image: $CI_REGISTRY/x-it-docker/docker-php:8.3-build-stable

variables:
  CUSTOMER_NAME: "CPSIT"
  PROJECT_NAME: 'quality-tools'
  COMPOSER_HOME: ${CI_PROJECT_DIR}/.composer

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - build
  - test

include:
  - '.gitlab-ci/**.yaml'

