---
image: $CI_REGISTRY/x-it-docker/docker-php:8.3-build-stable

variables:
  CUSTOMER_NAME: "CPSIT"
  PROJECT_NAME: 'quality-tools'
  COMPOSER_HOME: ${CI_PROJECT_DIR}/.composer

stages:
  - build
  - test

include:
  - '.gitlab-ci/**.yaml'

