#!/usr/bin/env php
<?php
// Mock typoscript-lint executable for testing configuration discovery
$configFile = null;
$args = array_slice($argv, 1);

for ($i = 0; $i < count($args); $i++) {
    $arg = $args[$i];
    if (($arg === '-c' || $arg === '--config') && isset($args[$i + 1])) {
        $configFile = $args[$i + 1];
        $i++;
    }
}

echo 'Config: ' . ($configFile ?? 'none') . PHP_EOL;
exit(0);
